# Generated by Django 5.2.7 on 2025-11-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIAuditDocument', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='Audit_Log_target__5d1b3b_idx',
            old_name='APIAuditDoc_target__90c081_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='Audit_Log',
        ),
    ]
