<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-12-03 17:39
=======
# Generated by Django 5.2.7 on 2025-12-03 17:45
>>>>>>> 7b76652 (style (AttachedFilesModal): component style remaked)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIEmpresa', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorUser',
            fields=[
                ('sector_user_id', models.BigAutoField(db_column='ID_sector_user', primary_key=True, serialize=False)),
                ('is_adm', models.BooleanField(db_column='is_administrator_sector_user', default=False)),
            ],
            options={
                'verbose_name': 'Vinculo entre Setor e Usuario',
                'verbose_name_plural': 'Vinculos entre Setores e Usuarios',
                'db_table': 'SectorUser',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.AutoField(db_column='PK_sector', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_sector', max_length=200)),
                ('image', models.ImageField(blank=True, db_column='image_sector', default='templates/sector_image_default.png', null=True, upload_to='sector_images/')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='date_created_at_sector')),
                ('is_active', models.BooleanField(db_column='is_active_sector', default=True)),
                ('enterprise', models.ForeignKey(db_column='FK_enterprise_sector', on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='APIEmpresa.enterprise')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'db_table': 'Sector',
            },
        ),
    ]
