# Generated by Django 5.2.7 on 2025-12-27 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APISetor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='manager',
            field=models.ForeignKey(db_column='FK_manager_sector', on_delete=django.db.models.deletion.CASCADE, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectorreviewpolicy',
            name='sector',
            field=models.OneToOneField(db_column='FK_sector_review_policy', on_delete=django.db.models.deletion.CASCADE, related_name='review_policy', to='APISetor.sector', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='sectoruser',
            name='sector',
            field=models.ForeignKey(db_column='FK_sector_sector_user', on_delete=django.db.models.deletion.CASCADE, related_name='sector_links', to='APISetor.sector'),
        ),
        migrations.AddField(
            model_name='sectoruser',
            name='user',
            field=models.ForeignKey(db_column='FK_user_sector_user', on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
