# Generated by Django 5.2.7 on 2025-12-04 20:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APISetor', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorReviewPolicy',
            fields=[
                ('review_policy_id', models.AutoField(db_column='PK_sector_review_policy', primary_key=True, serialize=False)),
                ('days', models.PositiveIntegerField(db_column='days_review_policy', default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hours', models.PositiveIntegerField(db_column='hours_review_policy', default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minutes', models.PositiveIntegerField(db_column='minutes_review_policy', default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sector', models.OneToOneField(db_column='FK_sector_review_policy', on_delete=django.db.models.deletion.CASCADE, related_name='review_policy', to='APISetor.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Política de Revisão',
                'verbose_name_plural': 'Políticas de Revisão',
                'db_table': 'Sector_Review_Policy',
            },
        ),
    ]
