# Generated by Django 5.2.7 on 2025-12-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APISetor', '0003_sectorreviewpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorreviewpolicy',
            name='is_active',
            field=models.BooleanField(db_column='is_active_sector_review_policy', default=False),
        ),
    ]
