# Generated by Django 5.2.7 on 2025-12-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APISetor', '0004_sectorreviewpolicy_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectorreviewpolicy',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='sectorreviewpolicy',
            name='minutes',
        ),
    ]
