# Generated by Django 5.2.7 on 2025-11-19 02:50

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('APIDocumento', '0001_initial'), 
        
    ]
    operations = [
        TrigramExtension(),
    ]