# Generated by Django 5.2.7 on 2025-12-27 20:13

import apps.core.utils
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attached_Files_Document',
            fields=[
                ('attached_file_id', models.AutoField(db_column='PK_attached_file', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title_attached_file', max_length=100)),
                ('file', models.FileField(db_column='file_attached_file', upload_to=apps.core.utils.rename_file_for_s3)),
                ('attached_at', models.DateTimeField(auto_now_add=True, db_column='date_attached_at_attached_file')),
                ('detached_at', models.DateTimeField(blank=True, db_column='date_detached_at_attached_file', null=True)),
            ],
            options={
                'verbose_name': 'Attached File',
                'verbose_name_plural': 'Attached Files',
                'db_table': 'Attached_Files_Document',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='PK_category', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='name_category', db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, db_column='description_category', null=True)),
                ('is_public', models.BooleanField(db_column='is_public_category', default=False)),
                ('color', models.CharField(blank=True, db_column='color_category', default='#FFFFFF', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification_id', models.AutoField(db_column='PK_classification', primary_key=True, serialize=False)),
                ('is_reviewed', models.BooleanField(db_column='review_status_classification', default=False)),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'db_table': 'Classification',
            },
        ),
        migrations.CreateModel(
            name='Classification_Privacity',
            fields=[
                ('privacity_id', models.AutoField(db_column='PK_classification_privacity', primary_key=True, serialize=False)),
                ('privacity', models.CharField(choices=[('Publico', 'Público'), ('Privado', 'Privado'), ('Exclusivo', 'Exclusivo')], db_column='privacity', default='Privado', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Classification Privacity',
                'verbose_name_plural': 'Classifications Privacies',
                'db_table': 'Classification_Privacity',
            },
        ),
        migrations.CreateModel(
            name='Classification_Status',
            fields=[
                ('status_id', models.AutoField(db_column='PK_status', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('C', 'Concluído'), ('E', 'Em andamento'), ('R', 'Revisão necessária'), ('A', 'Arquivado')], db_column='status', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Classification Status',
                'verbose_name_plural': 'Classifications Statuses',
                'db_table': 'Classification_Status',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(db_column='PK_document', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title_document', default='Novo Documento', max_length=200)),
                ('content', models.JSONField(blank=True, db_column='content_document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='date_created_at_document')),
                ('is_active', models.BooleanField(db_column='is_active_document', default=True)),
                ('file_url', models.FileField(blank=True, db_column='file_url_document', default=None, upload_to='uploaded_documents/')),
                ('thumbnail_path', models.FileField(blank=True, db_column='thumbnail_path_document', default=None, upload_to='thumbnails/')),
                ('search_content', models.TextField(blank=True, db_column='search_content_document', null=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('document_id', models.IntegerField(blank=True, db_column='PK_document', db_index=True)),
                ('title', models.CharField(db_column='title_document', default='Novo Documento', max_length=200)),
                ('content', models.JSONField(blank=True, db_column='content_document', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='date_created_at_document', editable=False)),
                ('is_active', models.BooleanField(db_column='is_active_document', default=True)),
                ('file_url', models.TextField(blank=True, db_column='file_url_document', default=None, max_length=100)),
                ('thumbnail_path', models.TextField(blank=True, db_column='thumbnail_path_document', default=None, max_length=100)),
                ('search_content', models.TextField(blank=True, db_column='search_content_document', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Document',
                'verbose_name_plural': 'historical Documents',
                'db_table': 'Document_Record',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
