# Generated by Django 5.2.7 on 2025-11-19 02:52

import apps.core.utils
import django.contrib.postgres.indexes
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIEmpresa', '__first__'),
        ('APISetor', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification_Privacity',
            fields=[
                ('classification_privacity_id', models.AutoField(db_column='PK_classification_privacity', primary_key=True, serialize=False)),
                ('privacity', models.CharField(choices=[('PB', 'Publico'), ('PV', 'Privado')], db_column='privacity_classification_privacity', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Classification Privacity',
                'verbose_name_plural': 'Classifications Privacies',
                'db_table': 'Classification_Privacity',
            },
        ),
        migrations.CreateModel(
            name='Classification_Status',
            fields=[
                ('status_id', models.AutoField(db_column='PK_status', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('C', 'Concluído'), ('E', 'Em andamento'), ('R', 'Revisão necessária'), ('A', 'Arquivado')], db_column='status', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Classification Status',
                'verbose_name_plural': 'Classifications Statuses',
                'db_table': 'Classification_Status',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='PK_category', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='name_category', db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, db_column='description_category', null=True)),
                ('is_public', models.BooleanField(db_column='is_public_category', default=False)),
                ('category_enterprise', models.ForeignKey(db_column='FK_enterprise_category', on_delete=django.db.models.deletion.CASCADE, to='APIEmpresa.enterprise')),
                ('category_sector', models.ForeignKey(blank=True, db_column='FK_sector_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APISetor.sector')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification_id', models.AutoField(db_column='PK_classification', primary_key=True, serialize=False)),
                ('is_reviewed', models.BooleanField(db_column='review_status_classification', default=False)),
                ('reviewer', models.ForeignKey(db_column='FK_reviewer_classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_by_user', to=settings.AUTH_USER_MODEL)),
                ('privacity', models.ForeignKey(db_column='FK_privacity_classification', null=True, on_delete=django.db.models.deletion.PROTECT, to='APIDocumento.classification_privacity')),
                ('classification_status', models.ForeignKey(db_column='FK_status_classification', default=None, on_delete=django.db.models.deletion.PROTECT, to='APIDocumento.classification_status')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'db_table': 'Classification',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(db_column='PK_document', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title_document', default='Novo Documento', max_length=200)),
                ('content', models.JSONField(blank=True, db_column='content_document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='date_created_at_document')),
                ('is_active', models.BooleanField(db_column='is_active_document', default=True)),
                ('categories', models.ManyToManyField(blank=True, db_column='FK_category_document', db_table='Document_Category', related_name='documents', to='APIDocumento.category')),
                ('classification', models.OneToOneField(blank=True, db_column='FK_classification_document', null=True, on_delete=django.db.models.deletion.PROTECT, to='APIDocumento.classification')),
                ('creator', models.ForeignKey(db_column='FK_creator_document', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(db_column='FK_sector_document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APISetor.sector')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Attached_Files_Document',
            fields=[
                ('attached_file_id', models.AutoField(db_column='PK_attached_file', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title_attached_file', max_length=100)),
                ('file', models.FileField(db_column='file_attached_file', upload_to=apps.core.utils.rename_file_for_s3)),
                ('attached_at', models.DateTimeField(auto_now_add=True, db_column='date_attached_at_attached_file')),
                ('detached_at', models.DateTimeField(blank=True, db_column='date_detached_at_attached_file', null=True)),
                ('document_id', models.ForeignKey(db_column='FK_document_attached_file', on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='APIDocumento.document')),
            ],
            options={
                'verbose_name': 'Attached File',
                'verbose_name_plural': 'Attached Files',
                'db_table': 'Attached_Files_Document',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('document_id', models.IntegerField(blank=True, db_column='PK_document', db_index=True)),
                ('title', models.CharField(db_column='title_document', default='Novo Documento', max_length=200)),
                ('content', models.JSONField(blank=True, db_column='content_document', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='date_created_at_document', editable=False)),
                ('is_active', models.BooleanField(db_column='is_active_document', default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('classification', models.ForeignKey(blank=True, db_column='FK_classification_document', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='APIDocumento.classification')),
                ('creator', models.ForeignKey(blank=True, db_column='FK_creator_document', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, db_column='FK_sector_document', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='APISetor.sector')),
            ],
            options={
                'verbose_name': 'historical Document',
                'verbose_name_plural': 'historical Documents',
                'db_table': 'Document_Record',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='document_content_gin_idx'),
        ),
    ]
