# Generated by Django 5.2.7 on 2025-12-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIDocumento', '0001_initial'),
        ('APIEmpresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_enterprise',
            field=models.ForeignKey(db_column='FK_enterprise_category', on_delete=django.db.models.deletion.CASCADE, to='APIEmpresa.enterprise'),
        ),
    ]
