# Generated by Django 5.2.7 on 2025-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIDocumento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, db_column='color_category', default='#FFFFFF', max_length=7, null=True),
        ),
    ]
