# Generated by Django 5.2.7 on 2025-12-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIDocumento', '0002_initial'),
        ('APISetor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_sector',
            field=models.ForeignKey(blank=True, db_column='FK_sector_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APISetor.sector'),
        ),
    ]
