# Generated by Django 5.2.7 on 2025-12-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIDocumento', '0003_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldocument',
            name='file_url',
            field=models.CharField(blank=True, db_column='file_url_document', default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='thumbnail_path',
            field=models.CharField(blank=True, db_column='thumbnail_path_document', default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.CharField(blank=True, db_column='file_url_document', default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail_path',
            field=models.CharField(blank=True, db_column='thumbnail_path_document', default=None, max_length=500),
        ),
    ]
