# Generated by Django 5.2.7 on 2025-12-27 20:13

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIDocumento', '0003_initial'),
        ('APISetor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='reviewer',
            field=models.ForeignKey(db_column='FK_reviewer_classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classification_privacity',
            name='exclusive_users',
            field=models.ManyToManyField(blank=True, db_table='Classification_Privacity_Exclusivity', related_name='exclusivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classification',
            name='privacity',
            field=models.ForeignKey(db_column='FK_privacity_classification', null=True, on_delete=django.db.models.deletion.PROTECT, to='APIDocumento.classification_privacity'),
        ),
        migrations.AddField(
            model_name='classification',
            name='classification_status',
            field=models.ForeignKey(db_column='FK_status_classification', default=None, on_delete=django.db.models.deletion.PROTECT, to='APIDocumento.classification_status'),
        ),
        migrations.AddField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, db_column='FK_category_document', db_table='Document_Category', related_name='documents', to='APIDocumento.category'),
        ),
        migrations.AddField(
            model_name='document',
            name='classification',
            field=models.OneToOneField(blank=True, db_column='FK_classification_document', null=True, on_delete=django.db.models.deletion.PROTECT, to='APIDocumento.classification'),
        ),
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(db_column='FK_creator_document', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='sector',
            field=models.ForeignKey(db_column='FK_sector_document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APISetor.sector'),
        ),
        migrations.AddField(
            model_name='attached_files_document',
            name='document_id',
            field=models.ForeignKey(db_column='FK_document_attached_file', on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='APIDocumento.document'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='classification',
            field=models.ForeignKey(blank=True, db_column='FK_classification_document', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='APIDocumento.classification'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='creator',
            field=models.ForeignKey(blank=True, db_column='FK_creator_document', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='sector',
            field=models.ForeignKey(blank=True, db_column='FK_sector_document', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='APISetor.sector'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='document_content_gin_idx'),
        ),
    ]
