# Generated by Django 5.2.7 on 2025-12-28 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIDocumento', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification_privacity',
            name='exclusive_users',
        ),
        migrations.AddField(
            model_name='classification',
            name='exclusive_users',
            field=models.ManyToManyField(blank=True, db_table='Classification_Privacity_Exclusivity', related_name='exclusivity', to=settings.AUTH_USER_MODEL),
        ),
    ]
