# Generated by Django 5.2.7 on 2025-12-30 08:43

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('APIDocumento', '0005_remove_classification_privacity_exclusive_users_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
