# Generated by Django 5.2.7 on 2025-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIDocumento', '0005_alter_document_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.FileField(blank=True, db_column='file_url_document', default=None, upload_to='uploaded_documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail_path',
            field=models.ImageField(blank=True, db_column='thumbnail_path_document', default=None, upload_to='thumbnails/'),
        ),
    ]
