# Generated by Django 5.2.7 on 2025-12-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIDocumento', '0006_alter_document_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file_path',
            field=models.FileField(max_length=500, upload_to='uploaded_documents/'),
        ),
    ]
