# Generated by Django 5.2.7 on 2025-12-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIDocumento', '0006_install_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='html_snapshot',
            field=models.TextField(blank=True, db_column='html_snapshot_document', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='yjs_state',
            field=models.BinaryField(blank=True, db_column='yjs_state_document', null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='html_snapshot',
            field=models.TextField(blank=True, db_column='html_snapshot_document', null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='yjs_state',
            field=models.BinaryField(blank=True, db_column='yjs_state_document', null=True),
        ),
    ]
