# Generated by Django 5.2.7 on 2025-12-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIDocumento', '0007_alter_mediaasset_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file_path',
            field=models.FilePathField(max_length=500, path='uploaded_documents/'),
        ),
    ]
