# Generated by Django 5.2.7 on 2025-12-27 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIDocumento', '0008_alter_mediaasset_file_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification_privacity',
            name='classification_privacity_id',
        ),
        migrations.RemoveField(
            model_name='classification_privacity',
            name='privacity',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='document',
            name='thumbnail_path',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='thumbnail_path',
        ),
        migrations.AddField(
            model_name='classification_privacity',
            name='exclusive_users',
            field=models.ManyToManyField(blank=True, db_table='Classification_Privacity_Exclusivity', related_name='exclusivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classification_privacity',
            name='is_exclusive',
            field=models.BooleanField(db_column='is_exclusive_status', default=False),
        ),
        migrations.AddField(
            model_name='classification_privacity',
            name='is_private',
            field=models.BooleanField(db_column='is_private_status', default=False),
        ),
        migrations.AddField(
            model_name='classification_privacity',
            name='is_public',
            field=models.BooleanField(db_column='is_public_status', default=False),
        ),
        migrations.AddField(
            model_name='classification_privacity',
            name='status_id',
            field=models.AutoField(db_column='PK_status', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='MediaAsset',
        ),
    ]
