# Generated by Django 5.2.7 on 2026-01-02 01:53

import apps.APIPayment.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Status',
            fields=[
                ('plan_status_id', models.AutoField(db_column='PK_plan_status', primary_key=True, serialize=False)),
                ('plan_status', models.CharField(db_column='plan_status', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Plan Status',
                'verbose_name_plural': 'Plan Statuses',
                'db_table': 'Plan_Status',
            },
        ),
        migrations.CreateModel(
            name='Plan_Type',
            fields=[
                ('plan_type_id', models.AutoField(db_column='PK_plan_type', primary_key=True, serialize=False)),
                ('plan_type', models.CharField(db_column='plan_type', max_length=50, unique=True)),
                ('price', models.DecimalField(db_column='price_type', decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, db_column='description_type', null=True)),
                ('features', models.JSONField(blank=True, db_column='features_type', null=True)),
            ],
            options={
                'verbose_name': 'Plan Type',
                'verbose_name_plural': 'Plan Types',
                'db_table': 'Plan_Type',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(db_column='PK_plan', primary_key=True, serialize=False)),
                ('asaas_customer_id', models.CharField(blank=True, db_column='asaas_customer_id_plan', max_length=50, null=True, unique=True)),
                ('asaas_subscription_id', models.CharField(blank=True, db_column='asaas_subscription_id_plan', max_length=50, null=True)),
                ('payment_link', models.URLField(blank=True, db_column='payment_link_plan', null=True)),
                ('next_due_date', models.DateField(blank=True, db_column='next_due_date_plan', null=True)),
                ('purchase_at', models.DateTimeField(auto_now=True, db_column='purchase_at_plan')),
                ('user', models.OneToOneField(db_column='FK_user_plan', on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
                ('status', models.OneToOneField(db_column='FK_plan_status', default=apps.APIPayment.models.Plan_Status.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='APIPayment.plan_status')),
            ],
        ),
    ]
