# Generated by Django 5.2.7 on 2026-01-03 12:25

import apps.APIPayment.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.ForeignKey(db_column='FK_plan_status', default=apps.APIPayment.models.Plan_Status.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='APIPayment.plan_status'),
        ),
    ]
