# Generated by Django 5.2.7 on 2026-01-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0002_alter_plan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-purchase_at'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.AlterModelTable(
            name='plan',
            table='Plan',
        ),
    ]
