# Generated by Django 5.2.7 on 2026-01-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0003_alter_plan_options_alter_plan_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_type',
            name='is_active',
            field=models.BooleanField(db_column='is_active_type', default=True),
        ),
    ]
