# Generated by Django 5.2.7 on 2026-01-08 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0004_plan_type_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Feature_Map',
            fields=[
                ('plan_feature_map_id', models.AutoField(db_column='PK_plan_feature_map', primary_key=True, serialize=False)),
                ('features', models.JSONField(blank=True, db_column='features_map', null=True)),
                ('plan', models.ForeignKey(db_column='FK_plan_type_map', on_delete=django.db.models.deletion.CASCADE, to='APIPayment.plan')),
            ],
            options={
                'verbose_name': 'Plan Feature Map',
                'verbose_name_plural': 'Plan Feature Maps',
                'db_table': 'Plan_Feature_Map',
            },
        ),
    ]
