# Generated by Django 5.2.7 on 2026-01-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIEmpresa', '0002_initial'),
        ('APIPayment', '0005_plan_feature_map'),
        ('APISetor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.ForeignKey(blank=True, db_column='FK_plan_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIPayment.plan_type'),
        ),
        migrations.CreateModel(
            name='PlanSubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(blank=True, db_column='FK_enterprise_plan_item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_plan_items', to='APIEmpresa.enterprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='APIPayment.plan')),
                ('sector', models.ForeignKey(blank=True, db_column='FK_sector_plan_item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_plan_items', to='APISetor.sector')),
            ],
            options={
                'verbose_name': 'Plan Subscription Item',
                'verbose_name_plural': 'Plan Subscription Items',
                'db_table': 'Plan_Subscription_Item',
            },
        ),
        migrations.DeleteModel(
            name='Plan_Feature_Map',
        ),
    ]
