# Generated by Django 5.2.7 on 2026-01-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIEmpresa', '0002_initial'),
        ('APIPayment', '0006_plan_plan_type_plansubscriptionitem_and_more'),
        ('APISetor', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanSubscriptionItem',
            new_name='Plan_Subscription_Item',
        ),
    ]
