# Generated by Django 5.2.7 on 2026-01-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIEmpresa', '0002_initial'),
        ('APIPayment', '0007_rename_plansubscriptionitem_plan_subscription_item'),
        ('APISetor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_subscription_item',
            name='enterprise',
            field=models.ForeignKey(blank=True, db_column='FK_enterprise_plan_item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_plan_items', to='APIEmpresa.enterprise', unique=True),
        ),
        migrations.AlterField(
            model_name='plan_subscription_item',
            name='sector',
            field=models.ForeignKey(blank=True, db_column='FK_sector_plan_item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_plan_items', to='APISetor.sector', unique=True),
        ),
    ]
