# Generated by Django 5.2.7 on 2026-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0008_alter_plan_subscription_item_enterprise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_subscription_item',
            name='id',
        ),
        migrations.AddField(
            model_name='plan_subscription_item',
            name='plan_subscription_item_id',
            field=models.AutoField(db_column='PK_plan_subscription_item', primary_key=True, serialize=False),
        ),
    ]
