# Generated by Django 5.2.7 on 2026-01-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0009_remove_plan_subscription_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_type',
            name='price',
            field=models.DecimalField(db_column='price_type', decimal_places=2, max_digits=10, null=True),
        ),
    ]
