# Generated by Django 5.2.7 on 2026-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0010_alter_plan_type_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_type',
            name='is_most_popular',
            field=models.BooleanField(db_column='is_most_popular_type', default=False),
        ),
        migrations.AddField(
            model_name='plan_type',
            name='order',
            field=models.PositiveIntegerField(db_column='order_type', default=0),
        ),
    ]
