# Generated by Django 5.2.7 on 2026-01-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0011_plan_type_is_most_popular_plan_type_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_type',
            name='is_free',
            field=models.BooleanField(db_column='is_free_type', default=False),
        ),
        migrations.AddField(
            model_name='plan_type',
            name='is_price_under_review',
            field=models.BooleanField(db_column='is_price_under_review_type', default=False),
        ),
    ]
