# Generated by Django 5.2.7 on 2026-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0012_plan_type_is_free_plan_type_is_price_under_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='payment_date',
            field=models.DateTimeField(blank=True, db_column='payment_date_plan', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='payment_expire_at',
            field=models.DateTimeField(blank=True, db_column='payment_expire_at_plan', null=True),
        ),
    ]
