# Generated by Django 5.2.7 on 2026-01-09 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0013_plan_payment_date_plan_payment_expire_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Discount',
            fields=[
                ('plan_discount_id', models.AutoField(db_column='PK_plan_discount', primary_key=True, serialize=False)),
                ('discount_title', models.CharField(blank=True, db_column='discount_title_plan_discount', max_length=100, null=True)),
                ('percentage', models.DecimalField(blank=True, db_column='percentage_plan_discount', decimal_places=2, max_digits=5, null=True)),
                ('fixed_value', models.DecimalField(blank=True, db_column='fixed_value_plan_discount', decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan_type',
            name='discount',
            field=models.ForeignKey(blank=True, db_column='FK_plan_discount', null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIPayment.plan_discount'),
        ),
    ]
