# Generated by Django 5.2.7 on 2026-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0014_plan_discount_plan_type_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_free_trial',
            field=models.BooleanField(db_column='is_free_trial_plan', default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='preferable_payment_day',
            field=models.PositiveIntegerField(blank=True, db_column='preferable_payment_day_plan', null=True),
        ),
        migrations.AddField(
            model_name='plan_type',
            name='free_trial_days',
            field=models.PositiveIntegerField(blank=True, db_column='free_trial_days_type', null=True),
        ),
    ]
