# Generated by Django 5.2.7 on 2026-01-12 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPayment', '0015_plan_is_free_trial_plan_preferable_payment_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='payment_expire_at',
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(db_column='FK_user_plan', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
