# Generated by Django 5.2.7 on 2025-12-03 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsUser',
            fields=[
                ('user_id', models.AutoField(db_column='PK_user', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_user', max_length=100)),
                ('username', models.CharField(db_column='username_user', max_length=50, unique=True)),
                ('email', models.EmailField(db_column='email_user', max_length=254, unique=True)),
                ('password', models.CharField(db_column='password_user', max_length=256)),
                ('image', models.ImageField(blank=True, db_column='image_user', default='templates/user_image_default.png', null=True, upload_to='user_images/')),
                ('date_joined', models.DateTimeField(auto_now=True, db_column='date_created_at_user')),
                ('last_login', models.DateTimeField(db_column='date_last_login_user', null=True)),
                ('is_active', models.BooleanField(db_column='is_active_user', default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('reset_id', models.AutoField(db_column='PK_password_reset', primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='token_password_reset', default=uuid.uuid4, max_length=48, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at_password_reset')),
                ('user', models.ForeignKey(db_column='FK_user_password_reset', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redefinir',
                'verbose_name_plural': 'Redefinir Senhas',
                'db_table': 'Password_Reset',
            },
        ),
    ]
