# Generated by Django 5.2.7 on 2026-01-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absuser',
            name='cpf_cnpj',
            field=models.CharField(blank=True, db_column='cpf_cnpj_user', max_length=20, null=True, unique=True),
        ),
    ]
