# Generated by Django 5.2.7 on 2026-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIUser', '0002_absuser_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='absuser',
            name='phone_mobile',
            field=models.CharField(blank=True, db_column='phone_mobile_user', max_length=20, null=True),
        ),
    ]
