# Generated by Django 5.2.7 on 2025-11-15 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=1, verbose_name='Ação')),
                ('target_model', models.CharField(db_column='target_audit', db_index=True, max_length=100)),
                ('target_id', models.IntegerField(db_column='target_id_audit', db_index=True)),
                ('target_str', models.CharField(db_column='target_tag_audit', db_index=True, max_length=200, verbose_name='Resumo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp_audit', db_index=True)),
                ('changes', models.JSONField(blank=True, db_column='changes_audit', default=dict, null=True)),
                ('actor', models.ForeignKey(db_column='PK_actor_audit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='APIAuditDoc_target__90c081_idx')],
            },
        ),
    ]
