# Generated by Django 5.2.7 on 2025-12-27 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('enterprise_id', models.AutoField(db_column='PK_enterprise', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_enterprise', max_length=100)),
                ('image', models.ImageField(blank=True, db_column='image_enterprise', null=True, upload_to='enterprise_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='date_created_at_enterprise')),
                ('is_active', models.BooleanField(db_column='is_active_enterprise', default=True)),
                ('owner', models.ForeignKey(db_column='FK_owner_enterprise', on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Enterprise',
            },
        ),
    ]
