# Generated by Django 5.2.7 on 2025-12-27 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIEmpresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='owner',
            field=models.ForeignKey(db_column='FK_owner_enterprise', on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to=settings.AUTH_USER_MODEL),
        ),
    ]
